"""Initial revision

Revision ID: d639afc21eed
Revises: 02a9a063bc70
Create Date: 2024-11-13 23:01:58.831611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd639afc21eed'
down_revision: Union[str, None] = '02a9a063bc70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderins', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column('orderins', sa.Column('summa', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderins', 'summa')
    op.drop_column('orderins', 'count')
    # ### end Alembic commands ###
